spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto는 애플리케이션 실행시점에 테이블을 다 지우고 다시 생성함
      ddl-auto: create
    properties:
      hibernate:
#        sout으로 로그를 찍음
#        show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
